eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.27:8761/eureka/
      
server:
  port: 8768

feign:
  hystrix:
    enabled: true
   
spring:
  application:
    name: eshop-one-service


